### ISSUE TITLE
White page in production

### ISSUE THREAD

**Issue by piervalli** [neomjs/admin-workspace#2]
Hello,

the app in developer mode works  correctly, instead in production there is a mising file
404 Not Found
http://127.0.0.1:8090/appworker.js

![image](https://user-images.githubusercontent.com/16557363/198825744-2df4f4d2-04f0-4b9b-81a4-993c26396ab3.png)

**Comment by tobiu** [comment]
the build is working fine on MacOS now. please let me know if this is not the case inside a windows based env.

**Comment by piervalli** [comment]
Hi 
when I compile there is that error




Executing post-build scripts
assets by chunk 149 KiB (id hint: vendors)
  asset chunks/main/968.js 82.7 KiB [compared for emit] [minimized] (id hint: vendors) 1 related asset
  asset chunks/main/297.js 45.2 KiB [compared for emit] [minimized] (id hint: vendors) 1 related asset
  asset chunks/main/718.js 21.3 KiB [compared for emit] [minimized] (id hint: vendors) 1 related asset
+ 19 assets
orphan modules 283 KiB [orphan] 62 modules
runtime modules 5.65 KiB 8 modules
built modules 479 KiB [built]
  modules by path ./node_modules/neo.mjs/src/ 225 KiB 27 modules
  modules by path ./node_modules/@material/ 218 KiB
    ./node_modules/@material/mwc-button/mwc-button.js + 15 modules 79 KiB [built] [code generated]
    + 3 modules
  modules by path ./node_modules/lit/ 15.3 KiB
    modules by path ./node_modules/lit/*.js 13.9 KiB 2 modules
    modules by path ./node_modules/lit/directives/*.js 1.48 KiB 2 modules
  modules by path ./node_modules/lit-html/*.js 8.34 KiB
    ./node_modules/lit-html/lit-html.js 7.87 KiB [built] [code generated]
    ./node_modules/lit-html/directive.js 481 bytes [built] [code generated]
  ./src/main/addon/ lazy ^\.\/.*\.mjs$ strict namespace object 160 bytes [built] [code generated]
  ./node_modules/tslib/tslib.es6.js 12 KiB [built] [code generated]
webpack 5.74.0 compiled successfully in 2448 ms
assets by status 57.4 KiB [cached] 3 assets
orphan modules 158 KiB [orphan] 25 modules
runtime modules 3.19 KiB 8 modules
built modules 224 KiB [built]
  modules by path ./node_modules/neo.mjs/src/core/*.mjs 16.2 KiB
    ./node_modules/neo.mjs/src/core/Base.mjs 14.4 KiB [built] [code generated]
    ./node_modules/neo.mjs/src/core/IdGenerator.mjs 1.83 KiB [built] [code generated]
  modules by path ./node_modules/neo.mjs/src/util/*.mjs 11.1 KiB
    ./node_modules/neo.mjs/src/util/VNode.mjs 7.02 KiB [built] [code generated]
    ./node_modules/neo.mjs/src/util/Array.mjs 4.12 KiB [built] [code generated]
  ./node_modules/neo.mjs/src/worker/App.mjs + 23 modules 163 KiB [built] [code generated]
  ../../../ lazy ^\.\/.*\.mjs$ include: [\\\/]app.mjs$ exclude: [\\\/]node_modules strict namespace object 160 bytes [built] [code generated]
  ./node_modules/neo.mjs/src/remotes/Api.mjs 1.91 KiB [built] [code generated]
  ./node_modules/neo.mjs/src/vdom/Helper.mjs + 2 modules 31.2 KiB [built] [code generated]

ERROR in ../../../ lazy ^\.\/.*\.mjs$ include: [\\\/]app.mjs$ exclude: [\\\/]node_modules strict namespace object
EBUSY: resource busy or locked, stat 'C:\DumpStack.log.tmp'
caused by plugins in ContextModule.resolveDependencies
Error: EBUSY: resource busy or locked, stat 'C:\DumpStack.log.tmp'
 @ ./node_modules/neo.mjs/src/worker/App.mjs 103:15-108:9

webpack 5.74.0 compiled with 1 error in 244189 ms
asset canvasworker.js 19.1 KiB [emitted] [minimized] (name: canvas)
orphan modules 73.5 KiB [orphan] 11 modules
runtime modules 88 bytes 1 module
built modules 75.8 KiB [built]
  ./node_modules/neo.mjs/src/worker/Canvas.mjs + 11 modules 75.6 KiB [built] [code generated]
  ./node_modules/neo.mjs/ lazy ^\.\/.*\/canvas\.mjs$ include: \/canvas.mjs$ exclude: \/node_modules strict namespace object 160 bytes [built] [code generated]
webpack 5.74.0 compiled successfully in 957 ms
asset dataworker.js 36 KiB [emitted] [minimized] (name: data)
asset chunks/data/72.js 2.48 KiB [emitted] [minimized]
asset chunks/data/647.js 2.34 KiB [emitted] [minimized]
asset chunks/data/283.js 532 bytes [emitted] [minimized]
orphan modules 111 KiB [orphan] 17 modules
runtime modules 3.19 KiB 8 modules
cacheable modules 158 KiB
  modules by path ./node_modules/neo.mjs/src/core/*.mjs 29.8 KiB
    ./node_modules/neo.mjs/src/core/Util.mjs 6.75 KiB [built] [code generated]
    ./node_modules/neo.mjs/src/core/Base.mjs 14.4 KiB [built] [code generated]
    ./node_modules/neo.mjs/src/core/Observable.mjs 6.82 KiB [built] [code generated]
    ./node_modules/neo.mjs/src/core/IdGenerator.mjs 1.83 KiB [built] [code generated]
  modules by path ./node_modules/neo.mjs/src/manager/ 58.9 KiB
    ./node_modules/neo.mjs/src/manager/rpc/Api.mjs 1.18 KiB [built] [code generated]
    ./node_modules/neo.mjs/src/manager/rpc/Message.mjs + 1 modules 8.32 KiB [built] [code generated]
    ./node_modules/neo.mjs/src/manager/Base.mjs + 4 modules 49.4 KiB [built] [code generated]
  ./node_modules/neo.mjs/src/worker/Data.mjs + 11 modules 58.9 KiB [built] [code generated]
  ./node_modules/neo.mjs/src/data/connection/WebSocket.mjs + 1 modules 9.99 KiB [built] [code generated]
webpack 5.74.0 compiled successfully in 1377 ms
asset serviceworker.js 19.2 KiB [emitted] [minimized] (name: service)
orphan modules 76.4 KiB [orphan] 11 modules
./apps/ServiceWorker.mjs + 11 modules 77.3 KiB [built] [code generated]
webpack 5.74.0 compiled successfully in 875 ms
asset vdomworker.js 28.9 KiB [emitted] [minimized] (name: vdom)
orphan modules 116 KiB [orphan] 16 modules
./node_modules/neo.mjs/src/worker/VDom.mjs + 16 modules 117 KiB [built] [code generated]
webpack 5.74.0 compiled successfully in 1040 ms

Total time for admin buildThreads: 271.15s

> admin@0.1.0 generate-docs-json
> node ./node_modules/neo.mjs/buildScripts/docs/jsdocx.mjs

Start default jsdocx parsing.
Default jsdocx parsing done.
jsdocx default parsing time: 14.21s
jsdocx custom parsing time: 0.14s

Total time for admin buildAll: 322.68s

C:\data\project-neo\admin-workspace>
